### ISSUE TITLE
MVM cards can use this kext?

### ISSUE THREAD

**Issue by saltpi** [rpeshkov/black80211#1]
MVM cards can use this kext? And could you make the latest release? I can help you test .

**Comment by tloki** [comment]
I see no commit or pull request that offer MVM supprot. Also, are you aware that this kext does not offer network connectivity? It's to early to "offer testing"...

**Comment by rpeshkov** [comment]
This project is not about MVM, DVM, Intel, Atheros, Broadcom or any other specific wireless adapter. This project is about reverse-engineering MacOS' wireless stack and providing fake information to it. I'm closing this issue.
